---
title: "Plesacov"
author: "Oleg Arnaut"
date: "2023-10-31"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = TRUE)

knitr::opts_chunk$set(dpi=300) 
knitr::opts_chunk$set(fig.width=7, fig.height=5) 

library(tidyverse)
library(forcats)
library(readxl)
library(openxlsx)
library(flextable)
library(dplyr)
library(gtsummary)
library(smd)


library(ggstatsplot)

# Define a function for grouped boxplots with nonparametric statistics
create_grouped_boxplot <- function(data, x_var, y_var, x_name, y_name) {
  plt <- ggbetweenstats(
    data = data,
    x = {{ x_var }},
    y = {{ y_var }},
    type = "nonparametric"
  )

  plt <- plt + 
    labs(
      x = x_name,
      y = y_name,
      #title = paste("Distribution of", quo_name(y_var), "by", quo_name(x_var))
    ) + 
    theme(
      text = element_text(family = "Roboto", size = 8, color = "black"),
      plot.title = element_text(
        family = "Lobster Two", 
        size = 12,
        face = "bold",
        color = "#2a475e"
      ),
      plot.subtitle = element_text(
        family = "Roboto", 
        size = 12, 
        face = "bold",
        color = "#1b2838"
      ),
      plot.title.position = "plot",
      axis.text = element_text(size = 10, color = "black"),
      axis.title = element_text(size = 12)
    )

  plt <- plt  +
    #ylim(0, max(data$y_var) + 5)+
    theme(
      axis.ticks = element_blank(),
      axis.line = element_line(colour = "grey50"),
      panel.grid = element_line(color = "#b4aea9"),
      panel.grid.minor = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(linetype = "dashed"),
      panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
      plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4")
    )
  
  return(plt)
}

```



# Dataset formation

```{r}


df <- read_excel("Baza de date Plesacov TURP.xlsx")


df %>% select(!c("Nr.", "Cod")) -> df 
  

# Identify character variables
character_vars <- sapply(df, is.character)

# Convert character variables to factors
df[character_vars] <- lapply(df[character_vars], as.factor)

names(df)

```

# General characteristics tables

```{r}

df$`Statut ECOG` <- as.factor(df$`Statut ECOG`)

#names(df[, 1:12])

df %>% 
  select("Vîrsta", "Statut ECOG", "Durata spitalizării", "Maladii CV",                        
         "Maladii TGI", "Maladii TU", "DZ", "Alfa adrenoblocante",               
         "Inhibitorii 5 Alfa reductaza", "Inhibitorii 5 Alfa fosfodiesteraza",
         "Durata bolii", "Tratament chirurgical" )  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()


```
# General characteristic graphs

```{r}


for (i in names(df[, c(2, 4, 5, 6, 7, 8, 9, 10, 11)])  ) {
  
p <- ggbarstats(df, x = "Tratament chirurgical", y = {{ i }})

p <- p +
  theme(
    text = element_text(family = "Roboto", size = 14, color = "black"),
    plot.title = element_text(
      family = "Lobster Two",
      size = 12,
      face = "bold",
      color = "#2a475e"
    ),
    plot.subtitle = element_text(
      family = "Roboto",
      size = 12,
      face = "bold",
      color = "#1b2838"
    ),
    plot.title.position = "plot",
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12)
  )

print(p)

}



```


```{r}

#names(df[, c(1, 3, 11, 12)])

create_grouped_boxplot(df, "Tratament chirurgical", "Vîrsta" , 'Tratament', 'Varsta, ani')



```

```{r}

create_grouped_boxplot(df, "Tratament chirurgical", "Durata spitalizării" ,
                           'Tratament', 'Spitalizarea, zile')

```


# Clinical characteristics tables


```{r}

library(dplyr)

#names(df[, 13:65])

# Assume 'df' is your data frame
numeric_vars <- df[, c(13:65)]

numeric_vars_list1 <- names(df[, c(13:65)])[sapply(df[, c(13:65)], is.numeric)]

numeric_vars_list <- c(numeric_vars_list1, "Tratament chirurgical")

```



```{r}

df[, numeric_vars_list] %>% 
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()


```




# Outcomes graphs


```{r}
# https://indrajeetpatil.github.io/ggstatsplot/index.html

# names(df[, 66:93])      

for (i in names(df[, 66:93])  ) {
  
p <- ggbarstats(df, x = "Tratament chirurgical", y = {{ i }})

p <- p +
  theme(
    text = element_text(family = "Roboto", size = 14, color = "black"),
    plot.title = element_text(
      family = "Lobster Two",
      size = 12,
      face = "bold",
      color = "#2a475e"
    ),
    plot.subtitle = element_text(
      family = "Roboto",
      size = 12,
      face = "bold",
      color = "#1b2838"
    ),
    plot.title.position = "plot",
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12)
  )

print(p)

}


```


# Outcomes Odds Ratio

```{r}


library(epitools)


for (i in names(df[, 66:93])  ) {
  
  var <- i
  print('______________________________________________________________')
  print(var)
  
  if (table(df[[var]])['Nu'] != 84) {
    
    contingency_table <- table(df$"Tratament chirurgical", df[[var]])
    print(oddsratio.fisher(contingency_table, rev = c("both"))$measure)
    
  }
  
}


# Inf in CI means that there is no way to estimate OR

```


# Outcomes tables

```{r, error = FALSE}

df %>% 
  select("Tratament chirurgical", "Disurie, preoperator", "Disurie,3 luni", "Disurie, 6 luni", "Disurie, 12 luni")  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()

# Error because it is not possible to estimate significance for constant variables

```


```{r, error = FALSE}

df %>% 
  select("Tratament chirurgical", "PZ, preoperator", "PZ, 3 luni", "PZ, 6 luni", "PZ, 12 luni")  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()



```



```{r, error = FALSE}

df %>% 
  select("Tratament chirurgical", "PN, preoperator", "PN, 3 luni", "PN, 6 luni", "PN, 12 luni")  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()



```


```{r}

df %>% 
  select("Tratament chirurgical", "DT, preoperator", "DT, 3 luni",  "DT, 6 luni", "DT, 12 luni" )  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()


```



```{r, error = FALSE}

df %>% 
  select("Tratament chirurgical", "GI, preoperator", "GI, 3 luni",  "GI, 6 luni", "GI, 12 luni" )  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()

# Error because it is not possible to estimate significance for constant variables

```
                              

```{r, error = FALSE}

df %>% 
  select("Tratament chirurgical", "UM, preoperator", "UM, 3 luni", "UM, 6 luni", "UM, 12 luni")  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()

# Error because it is not possible to estimate significance for constant variables

```
                               
                            
                              
```{r, error = FALSE}

df %>% 
  select("Tratament chirurgical", "RAU, preoperator", "RAU, 3 luni", "RAU, 6 luni", "RAU, 12 luni" )  %>%
  tbl_summary(by = "Tratament chirurgical",
              statistic = list(all_categorical() ~ "{n} ({p}%)",
                               all_continuous() ~ "{mean} ({sd})\n {median} ({IQR})\n {min} {max} "),
              digits = list(all_categorical() ~ c(0, 1),
                            all_continuous()  ~ c(1, 1))) %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("Participant characteristics") %>%
  bold_labels()%>%add_ci()%>%add_p()

# Error because it is not possible to estimate significance for constant variables

```

                              



   


